-- return {
-- 	'williamboman/mason.nvim',
-- 	dependencies = {
-- 		'williamboman/mason-lspconfig.nvim',
-- 		'WhoIsSethDaniel/mason-tool-installer.nvim',
-- 	},
-- 	config = function()
--
-- 		local mason = require('mason')
-- 		local mason_lspconfig = require('mason-lspconfig')
-- 		local mason_tool_installer = require('mason-tool-installer')
--
-- 		mason.setup({
-- 			ui = {
-- 				icons = {
-- 					package_installed = "✓",
-- 					package_pending = "➜",
-- 					package_uninstalled = "✗",
-- 				},
-- 			},
-- 		})
--
-- 		-- mason_lspconfig.setup({
-- 		-- 	-- LSP servers to install automatically
-- 		-- 	ensure_installed = {
-- 		-- 		'lua_ls',
-- 		-- 		'html',
-- 		-- 		'cssls',
-- 		-- 		'pylsp',
-- 		-- 		'clangd',
-- 		-- 		'rust_analyzer'
-- 		-- 	},
-- 		-- })
--
-- 		-- mason_tool_installer.setup({
-- 		-- 	-- Non-LSP tools to install automatically
-- 		-- 	ensure_installed = {
-- 		-- 		'prettier',
-- 		-- 		'isort',
-- 		-- 	}
-- 		-- })
--
-- 	end,
-- }
--
