import = ["/home/xander/.config/alacritty/catppuccin-mocha.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[env]
TERM = "xterm-256color"

[font]
size = 12

[font.bold]
family = "Fira Code  Nerd Font"
style = "Bold"

[font.bold_italic]
family = "Fira Code  Nerd Font"
style = "BoldItalic"

[font.italic]
family = "Fira Code  Nerd Font"
style = "MediumItalic"

[font.normal]
family = "Fira Code  Nerd Font"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[shell]
program = "/bin/bash"

[window]
opacity = 1

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10
